# Generated by Django 3.0 on 2020-01-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='conf_num',
            field=models.CharField(default='1', max_length=15),
            preserve_default=False,
        ),
    ]
